# Generated by Django 5.1.2 on 2025-04-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_thesis_cloudinary_url_alter_thesis_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thesis',
            old_name='cloudinary_url',
            new_name='gdrive_url',
        ),
    ]
