# Generated by Django 5.1.2 on 2025-04-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_rename_cloudinary_url_thesis_gdrive_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
