# Generated by Django 5.1.2 on 2025-04-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_program_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='embedding_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
